package kmf::grammars;

grammar ebnf {

  rules = rule+ ;
  rule = NAME '=' choice ';' ;
  choice = (item+ / '|')+ ;
  item = optional | multi | group | nonTerm | terminal ;
  optional = '[' choice ']' ;
  multi = item ('*' | '+') ;
  group = '(' choice ')' ;
  nonTerm = NAME ;
  terminal = LITERAL | PATTERN ;
  LITERAL = "\x27[^\x27]*\x27" ;
  PATTERN = "\x22[^\x22]*\x22" ;
  NAME = "[a-zA-Z_][a-zA-Z_0-9]*";

}