package kmf::grammars;

grammar kbnf extends ebnf2 {

  grammarFile = packageDef grammarSpec ;
  packageDef = 'package' pathName ';' ;
  grammarSpec = 'grammar' NAME ['extends' ( pathName / ',')+ ]
                ['OPTIONS' '(' option* ')']
                '{' rule+ '}' ;
  option = NAME '=' (NAME | PATTERN) ;
  pathName = (NAME / '::')+ ;
  item = list | optional | multi | group | nonTerm | terminal ;
  list = '(' item '/' terminal ')' '+' ;

}